Put vacation requests
JayReturns/SE-UnternehmenB pull request #81
Opened 2023-05-19 11:15 UTC by EpikMaik

2023-05-19 18:49 UTC, cherd31 requested changes
bis auf die Sache mit dem status und rejection_cause nur code Verschönerungen, keine Fehler

2023-05-19 18:49 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +            }
gucke bitte, wie das Überlappen in der POST Methode überprüft wird
ich finde das besser gelöst als mit diesem kompliziertem Stream....

2023-05-19 18:49 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +            logger.atInfo().log(vRequest.getVacationStart().toString() + " hier jetzt das enddatum: " + vRequest.getVacationEnd().toString());
bitte entferne nicht mehr benötigte logs und Kommentare bevor du den Branch mergest

2023-05-19 18:49 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        vacationRequestRepository.save(vRequest);
Datenbankoperationen sollten mit einem try-catch Statement umrandet werden

2023-05-19 18:49 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        if(status != null || rejection_cause != null){
status und rejection_cause können nie geändert werden (auch nicht von einem Manger)

2023-05-19 18:53 UTC, BerniProgrammer commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +            }
wir waren da in ein paar Fehler gelaufen, als wir noch hinzufügen wollten, dass alle Anträge außer dem aktuellen, den wir updaten wollen überprüfen. Ansonsten würde bei Änderung eines Datums immer zu einem Ablehnen führen.
Das war bis dato das Einzige, was funktioniert hatte.

2023-05-19 18:54 UTC, BerniProgrammer commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        vacationRequestRepository.save(vRequest);
theoretisch haben wir dafür den GlobalExceptionHandler

2023-05-19 18:55 UTC, BerniProgrammer commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        if(status != null || rejection_cause != null){
doch wenn der Manager den Antrag annimmt/ablehnt. Rückgängig machen wäre dann für den Manager auch möglich

2023-05-19 18:55 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +            }
okay alles klar

2023-05-19 18:56 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        if(status != null || rejection_cause != null){
habs gerade extra ausprobier, ging nicht

2023-05-19 18:56 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        vacationRequestRepository.save(vRequest);
okay alles klar

2023-05-19 18:58 UTC, cherd31 commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +        if(status != null || rejection_cause != null){
ich glaube da sollte nen `else if` hin

2023-05-19 19:01 UTC, BerniProgrammer commented on Backend/ssp/src/main/java/com/dhbw/unternehmenb/ssp/controller/MainServerController.java
> +            List<VacationRequest> allVacations = vacationRequestRepository.findAllByUser(currentUser);
das ist der falsche User. Man müsste den User von der gefundenen Request nehmen
GL soll ja auch Anträge von einem anderen Nutzer anpassen können

2023-05-20 15:02 UTC, cherd31 approved these changes
👍

2023-05-21 14:54 UTC, merged